// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package blockchain

import "sync"

// cat generic_ccmap.go | genny gen "String=string Block=*blockchain.Transaction" > [targetName].go

// BlockDictionary the set of Items
type BlockMap struct {
	items map[string]Block
	lock  sync.RWMutex
}

// Set adds a new item to the ccmap
func (d *BlockMap) Set(k string, v Block) {
	d.lock.Lock()
	defer d.lock.Unlock()
	if d.items == nil {
		d.items = make(map[string]Block)
	}
	d.items[k] = v
}

// Delete removes a value from the ccmap, given its key
func (d *BlockMap) Delete(k string) bool {
	d.lock.Lock()
	defer d.lock.Unlock()
	_, ok := d.items[k]
	if ok {
		delete(d.items, k)
	}
	return ok
}

// Has returns true if the key exists in the ccmap
func (d *BlockMap) Has(k string) bool {
	d.lock.RLock()
	defer d.lock.RUnlock()
	_, ok := d.items[k]
	return ok
}

// Get returns the value associated with the key
func (d *BlockMap) Get(k string) Block {
	d.lock.RLock()
	defer d.lock.RUnlock()
	return d.items[k]
}

// Clear removes all the items from the ccmap
func (d *BlockMap) Clear() {
	d.lock.Lock()
	defer d.lock.Unlock()
	d.items = make(map[string]Block)
}

// Size returns the amount of elements in the ccmap
func (d *BlockMap) Size() int {
	d.lock.RLock()
	defer d.lock.RUnlock()
	return len(d.items)
}

// Strings returns a slice of all the keys present
func (d *BlockMap) GetKys() []string {
	d.lock.RLock()
	defer d.lock.RUnlock()
	keys := []string{}
	for i := range d.items {
		keys = append(keys, i)
	}
	return keys
}

// Blocks returns a slice of all the values present
func (d *BlockMap) GetVals() []Block {
	d.lock.RLock()
	defer d.lock.RUnlock()
	values := []Block{}
	for i := range d.items {
		values = append(values, d.items[i])
	}
	return values
}
